name: Build omniLens-AI APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # <- 18 ki jagah 20 kar diya
    
    - name: Install dependencies
      run: npm install
    
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - uses: android-actions/setup-android@v3
    
    - name: Generate Android project
      run: npx expo prebuild --platform android --clean
    
    - name: Make gradlew executable
      run: chmod +x android/gradlew
    
    - name: Build Debug APK
      run: cd android && ./gradlew assembleDebug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: omniLens-AI-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
