- name: Generate Android project
  env:
    CI: 1
    EXPO_NO_PROMPT: 1
  run: npx expo prebuild --platform android --clean --yes

- name: Verify android folder
  run: ls -la android/

- name: Install updated dependencies
  run: npm install

- name: Make gradlew executable
  run: chmod +x android/gradlew

- name: Build Debug APK
  run: cd android && ./gradlew assembleDebug --no-daemon
